# Generated by Django 2.1 on 2022-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FileField(upload_to=''),
        ),
    ]
